# Generated by Django 2.2.16 on 2021-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', verbose_name='Описание пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('anonymous', 'Анонимный'), ('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', error_messages={'max_length': 'Превышена длинна роли пользователя'}, max_length=16, verbose_name='Тип пользователя'),
        ),
    ]
